import { NgModule } from "@angular/core";
import { BrowserModule } from "@angular/platform-browser";
import {
  DxAccordionModule,
  DxAutocompleteModule,
  DxButtonModule,
  DxCheckBoxModule,
  DxDataGridModule,
  DxDateBoxModule,
  DxDrawerModule,
  DxFormModule,
  DxListModule,
  DxLoadIndicatorModule,
  DxLoadPanelModule,
  DxMenuModule,
  DxNumberBoxModule,
  DxPopupModule,
  DxRadioGroupModule,
  DxResponsiveBoxModule,
  DxScrollViewModule,
  DxSelectBoxModule,
  DxSliderModule,
  DxTagBoxModule,
  DxTemplateModule,
  DxTextAreaModule,
  DxTextBoxModule,
  DxToastModule,
  DxToolbarModule,
  DxTooltipModule,
  DxTreeListModule,
  DxValidationSummaryModule,
  DxValidatorModule,
} from "devextreme-angular";
@NgModule({
  declarations: [],
  imports: [
    DxButtonModule,
    DxTextBoxModule,
    DxFormModule,
    DxFormModule,
    DxSelectBoxModule,
    DxCheckBoxModule,
    DxDateBoxModule,
    DxValidatorModule,
    DxValidationSummaryModule,
    DxAccordionModule,
    DxSliderModule,
    DxTagBoxModule,
    DxTemplateModule,
    DxLoadIndicatorModule,
    DxLoadPanelModule,
    DxPopupModule,
    DxScrollViewModule,
    DxListModule,
    DxNumberBoxModule,
    DxTooltipModule,
    DxDataGridModule,
    DxTextAreaModule,
    DxResponsiveBoxModule,
    DxAutocompleteModule
  ],
  exports: [
    DxButtonModule,
    DxTextBoxModule,
    DxFormModule,
    DxFormModule,
    DxSelectBoxModule,
    DxCheckBoxModule,
    DxDateBoxModule,
    DxValidatorModule,
    DxValidationSummaryModule,
    DxAccordionModule,
    DxSliderModule,
    DxTagBoxModule,
    DxTemplateModule,
    DxLoadIndicatorModule,
    DxLoadPanelModule,
    DxPopupModule,
    DxScrollViewModule,
    DxListModule,
    DxNumberBoxModule,
    DxTooltipModule,
    DxDataGridModule,
    DxTextAreaModule,
    DxResponsiveBoxModule,
    DxMenuModule,
    DxAutocompleteModule,
    DxDrawerModule,
    DxRadioGroupModule,
    DxToolbarModule,
    DxToastModule,
    DxTreeListModule,
  ],
  providers: [],
  bootstrap: [],
})
export class DevExtremeModuleModule {}
